### ISSUE TITLE
Figure out project standards for code linting, formatting and import order

### ISSUE THREAD

**Issue by audiodude** [noisebridge/MediaBridge#18]
Probably the best choice is [black](https://black.readthedocs.io/en/stable/index.html), which is used by lots of the official Python projects. There's also [ruff](https://docs.astral.sh/ruff/) which is supposedly faster, but I doubt it will matter for the handful of Python files we'll have. Not sure if either of these provide import formatting, I know about [isort](https://pycqa.github.io/isort/) for that.

Also as far as enforcing these, we can just trust everyone to install the formatters in their VSCode or other editors, or we can create git "hooks" that enforce it every time you commit (but that requires setting up a library like [pre-commit](https://pre-commit.com/) which can be bypassed), or we can set up a GitHub action that tries to do the formatting and fails if there are any changes. The GitHub action would be configured as a "check" so that PRs that violate it (aren't formatted) wouldn't be able to be checked in.

Discuss your ideas and opinions here.

**Comment by jhanley634** [comment]
I offer [this](https://github.com/jhanley634/dojo-blackboard/blob/main/.pre-commit-config.yaml) as an example of hooks that work quite well in practice. The DX education aspect to it is we should demonstrate a "failing" commit, e.g. deliberately adding trailing whitespace to a file or adding out-of-lexical-order deps to requirements.txt. And tell students that if there was a Red message, then it is like "the commit never happened". So we can `git diff` to see what the auto-fix was. And hit up-arrow or `!!` to repeat the commit and this time it will have effect, it will succeed.

In several industrial settings I have used a variety of linters, as part of a team of colleagues having diverse abilities. I find some linters are entirely too strict, and not worth educating developers about when to obey or ignore a given diagnostic. I find that `ruff` is on the permissive side and should _always_ be obeyed at PR time, even if only to shut it up. Ignoring its complaint about e.g. "unused import" is perfectly fine for frequent WIP commits that precede a PR submission. It is _always_ fine to run `$ black *.py` and to run `$ isort *.py`. It usually takes just under 1 second to run them along with `$ ruff check *.py` on a codebase of modest size, so it's a good fit for a rapid edit-debug cycle.

Isort performs a distinct task from black -- it is necessary to run both together, perhaps running black on every edit and isort on every sixth edit or so. Isort creates the three groups specified by [PEP-8](https://peps.python.org/pep-0008/#imports), and yes, it really is easier for a reviewer to read code which has been formatted in that way.

The first time we run `black` on a new codebase it can be helpful to specify `black -S .`, so single-quote strings don't arbitrarily get converted to double-quote. It's just a matter of minimizing diffs. After folks get used to it, no one will care. A project that adopts black should definitely specify `black .` with no options. Interestingly, `main` currently has no text literals which would be affected by that.

You may find that engineers change how they code in two ways when using black:
1. To get something to layout as desired, we might choose to introduce a named temporary expression, so the final function call fits within a line.
2. Tacking on an "extra" trailing `,` comma will sometimes make formatted args or a list more aesthetically pleasing.

I recommend adding something like this to pyproject.toml:
```
[tool.black]
line-length = 100

[tool.isort]
float_to_top =            true
include_trailing_comma =  true
multi_line_output =       "VERTICAL_HANGING_INDENT"
line_length =             100
```

**Comment by jhanley634** [comment]
As an orthogonal aspect, I recommend _not_ requiring that PRs must do type annotation which passes `$ mypy --strict *.py`. However, you might possibly choose to produce "cleanup PRs" which add type annotation after-the-fact. It will have the effect of encouraging committers to at least consider adding the optional type annotation.

Such practice carries a few benefits:
1. Static type safety analysis can **prove** that certain failure modes are impossible, such as calling `.lower()` on a putative string which might actually be `None`.
2. Function docstrings tend to be more concise, when the signature has _already_ explained that an input arg is e.g. `s: str` or `s: str | None`.

The gold standard here is `mypy`. I find that if I can get some code past that, in strict mode, then I can nearly always get it past Microsoft's `pyright`, as well. I find that Meta's `pyre check` and Google's `pytype` are kind of a pain-in-the-neck to integrate into such a development flow. I'm sure running each of them _alone_ works well for those respective organizations. But the whole business of different tools noticing different sets of symptoms and needing different "ignore" comments gets to be a bit nightmarish, especially when they complain about an "ignore" which "wasn't needed" since that tool doesn't notice details which another tool does. Recommend you rely on `mypy` plus maybe `pyright`, and ignore the other two contenders. Recommend that you _not_ make "type safe" a requirement for merging a PR down to `main`.

**Comment by audiodude** [comment]
Thank you for the interesting insights and sample configurations.

What are your thoughts on the alternatives discussed in the OP? Specifically

1. Trust developers to do formatting in VSCode or on the command line
2. Install `pre-commit` in the git repo, with the caveat that developers can just fail to install it and bypass the checks
3. Create PR "checks" that enforce formatting before a PR can be checked in

It seems to me that 3) is the only way to conclusively ensure that the code is always formatted correctly in the repo. As you pointed out, 2) can be cumbersome when trying to check in WIP.

It seems we need some combination of the above?

Additionally, I've never discussed type checking in any of the Python classes, not sure if it's a good idea to introduce it now or if it will cause too much friction.

**Comment by audiodude** [comment]
After discussing tonight, we're going to go with #3: Use a GitHub action/check to enforce formatting before code can be checked in. I'll work on it in the next week.

**Comment by audiodude** [comment]
Decided to use [ruff](https://docs.astral.sh/ruff/) with 4 space indentation. Will work on creating a config.

**Comment by skyfenton** [comment]
Closing issue since it looks like the PR didn't automatically do it (prob b/c branch was merged into another branch?)
