### ISSUE TITLE
Main.py ModuleNotFoundError: No module named 'mediabridge'

### ISSUE THREAD

**Issue by skyfenton** [noisebridge/MediaBridge#39]
I don't think the import is working with the main.py file on the main branch, but idk if other machines are different.

```
Traceback (most recent call last):
  File "/workspaces/MediaBridge/mediabridge/main.py", line 1, in <module>
    from mediabridge.data_processing import wiki_to_netflix
ModuleNotFoundError: No module named 'mediabridge'
```

Obviously `from data_processing import ___` works, but I know we prefer the `mediabridge.*` format and I don't know if we're just missing something (other than moving the main.py file out of the directory).

**Comment by audiodude** [comment]
What is the command you're using to run the main script? It needs to be run as part of the `mediabridge` "module". Additionally, you need to prefix the run command with `pipenv run` so that the required libraries are loaded. So the full command, from the root directory, is:

```
pipenv run python -m mediabridge.main
```

I'll document this in the README and then close this issue.

**Comment by skyfenton** [comment]
Ah I was just in the pipenv shell running python main.py. Moving to #40 for discussion.
